language: node_js
node_js: "stable"

dist: bionic

services:
 - xvfb

addons:
  firefox: "latest"
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - fluxbox >/dev/null 2>&1 &
  - sleep 3
